#!/bin/bash

tasks=(
    "high_school_european_history"
    "business_ethics"
    "clinical_knowledge"
    "medical_genetics"
    "high_school_us_history"
    "high_school_physics"
    "high_school_world_history"
    "virology"
    "high_school_microeconomics"
    "econometrics"
    "college_computer_science"
    "high_school_biology"
    "abstract_algebra"
    "professional_accounting"
    "philosophy"
    "professional_medicine"
    "nutrition"
    "global_facts"
    "machine_learning"
    "security_studies"
    "public_relations"
    "professional_psychology"
    "prehistory"
    "anatomy"
    "human_sexuality"
    "college_medicine"
    "high_school_government_and_politics"
    "college_chemistry"
    "logical_fallacies"
    "high_school_geography"
    "elementary_mathematics"
    "human_aging"
    "college_mathematics"
    "high_school_psychology"
    "formal_logic"
    "high_school_statistics"
    "international_law"
    "high_school_mathematics"
    "high_school_computer_science"
    "conceptual_physics"
    "miscellaneous"
    "high_school_chemistry"
    "marketing"
    "professional_law"
    "management"
    "college_physics"
    "jurisprudence"
    "world_religions"
    "sociology"
    "us_foreign_policy"
    "high_school_macroeconomics"
    "computer_security"
    "moral_scenarios"
    "moral_disputes"
    "electrical_engineering"
    "astronomy"
    "college_biology"
)

COLLECTED_DIR="./lcollected_metrics/"
mkdir -p "$COLLECTED_DIR"

for task in "${tasks[@]}"
do
    echo "running task: $task"

    python3 src/eval.py model=text_otf data=mmlu data.dataset_partial.task="$task" +hydra.run.dir="./logs/eval/runs/$task"

    metrics_path="./logs/eval/runs/$task/csv/version_0/metrics.csv"

    if [ -f "$metrics_path" ]; then
        cp "$metrics_path" "$COLLECTED_DIR/$task.csv"
        echo "save to: $COLLECTED_DIR/$task.csv"
    else
        echo "lost metrics.csv: $metrics_path"
    fi
done

echo "Done collection metrics.csv files。"