defaults:
  - llm: llama
  - _self_

_target_: src.models.text_otf_module.LanguageTaskOnTheFlyLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

characters:
  [ "management expert",
    "medical genetics expert",
    # "machine learning expert",
    # "sociology expert", 
    # "computer science expert",
    # "philosophy expert",
    # "anatomy expert",
    # "electrical engineering expert",
    # "biology expert",
    # "marketing expert",
    # "history expert",
    # "economics expert",
    # "physics expert",
    # "mathematics expert",
    # "chemistry expert",
    # "psychology expert",
    # "law expert",
    # "primary school student",
    # "high school students",
    # "taxi driver",
    # "farmer",
    # "senior doctor",
    # "senior engineer"
  ]

template: "You are a {character}, You are a {character}, You are a {character}, would you answer the following question with A, B, C or D? \n Question: {context}\n Answer: "
  
num_classes: ${data.dataset_partial.num_classes}
seed: ${seed}

data_path: ${paths.data_dir}

extract_hidden: False 
