import json
import os


# Management (label 0) sentences
management_sentences = [
    "This individual is a master of coordination and strategy, often acting as the driving force behind a team's success. With exceptional leadership skills, they excel at allocating resources, optimizing workflows, and ensuring everyone is aligned toward a common goal. They have a knack for solving complex organizational problems, turning challenges into opportunities for growth. Their role involves planning, decision-making, and motivating others to achieve peak performance. Known for their ability to adapt to changing circumstances, they often wear many hats and are seen as the cornerstone of any successful operation.",
    "A visionary leader who seamlessly blends analytical thinking with emotional intelligence, navigating complex organizational landscapes with remarkable precision. They possess an uncanny ability to anticipate market trends, develop strategic roadmaps, and inspire teams to transcend their perceived limitations. Their approach combines data-driven insights with intuitive understanding of human dynamics.",
    "A strategic maestro who transforms organizational chaos into structured excellence. With laser-focused attention to detail and a panoramic view of business ecosystems, they design sophisticated systems that enhance productivity, foster innovation, and create sustainable competitive advantages. Their leadership is both a science and an art.",
    "An exceptional professional who embodies the perfect blend of technical proficiency and human-centric leadership. They understand that successful organizational success is not just about processes and metrics, but about nurturing talent, creating empowering environments, and building resilient cultures that can withstand rapid technological and market changes.",
    "A true organizational architect who designs intricate frameworks of collaboration, communication, and performance. Their expertise lies in understanding the subtle interconnections between people, processes, and technology. They can diagnose systemic inefficiencies and implement transformative solutions that unlock an organization's latent potential.",
    "A strategic thinker possessing an extraordinary capacity for holistic problem-solving. They view challenges not as obstacles, but as opportunities for organizational learning and growth. Their ability to synthesize complex information, make decisive choices, and lead with empathy makes them an invaluable asset in any business environment.",
    "A dynamic professional who excels at bridging strategic vision with tactical execution. They possess an innate talent for reading organizational dynamics, identifying hidden potential in teams, and creating alignment between individual aspirations and collective goals. Their approach is both systematic and deeply human.",
    "An adaptive leader who thrives in uncertainty, turning complexity into competitive advantage. They are skilled at developing agile strategies, fostering innovation, and creating organizational ecosystems that can rapidly respond to changing market conditions. Their leadership is characterized by continuous learning and proactive adaptation.",
    "A master of organizational alchemy, transforming raw potential into high-performance outcomes. They understand the delicate balance between structure and flexibility, using sophisticated leadership techniques to motivate, align, and empower diverse teams towards extraordinary achievements.",
    "This individual possesses exceptional organizational skills, enabling them to coordinate multiple projects simultaneously while maintaining a clear vision of the big picture. Their structured approach and ability to assign tasks effectively drive teams toward achieving ambitious goals.",
    "This individual possesses exceptional organizational skills, enabling them to manage multiple projects simultaneously while maintaining a clear vision of the big picture. Their structured approach and ability to delegate tasks effectively drive teams toward achieving ambitious goals.",
    "With a talent for strategic planning, this expert can break down complex challenges into manageable steps, ensuring every resource is utilized to its full potential. They are admired for their calm demeanor under pressure and their ability to guide teams through uncertain times.",
    "A master of communication, this individual builds strong relationships with team members, stakeholders, and clients alike. They inspire trust and confidence through transparency, fostering a collaborative work environment where innovation thrives.",
    "Renowned for their analytical skills, this expert evaluates performance metrics, identifies bottlenecks, and implements solutions that optimize productivity. They excel at balancing long-term vision with short-term priorities, ensuring sustainable growth.",
    "This leader thrives in high-stakes environments, making tough decisions with a combination of data-driven insights and intuition. Their forward-thinking mindset allows them to anticipate challenges and develop contingency plans to stay ahead of the curve.",
    "Driven by results, this individual ensures that every action aligns with organizational objectives. Their ability to inspire teams, set clear expectations, and track progress makes them an invaluable asset to any business or project.",
    "This expert is highly adaptable, thriving in dynamic environments where change is constant. They bring a proactive attitude, adjusting strategies in real time to keep projects on track and delivering consistent outcomes.",
    "With a keen eye for detail and a passion for efficiency, this individual optimizes workflows, reduces redundancies, and ensures seamless coordination across departments. Their systematic approach enhances both team performance and overall morale.",
    "As a natural problem-solver, this expert embraces challenges as opportunities to innovate. They approach obstacles with creativity, turning setbacks into stepping stones for success and motivating their team to do the same.",
    "This individual leads by example, embodying dedication, accountability, and integrity. They cultivate a culture of excellence by empowering team members, encouraging professional development, and celebrating collective achievements."
]

# Medical Genetics Expert (label 1) sentences
genetics_sentences = [
    "This individual is a master of decoding complex biological puzzles, often acting as the driving force behind groundbreaking discoveries in human biology. With exceptional analytical skills, they excel at unraveling intricate biological patterns, interpreting molecular data, and ensuring tailored health solutions. They have a knack for solving challenging genetic disorders, turning genetic complexities into opportunities for targeted treatments. Their role involves research, diagnostic analysis, and pioneering innovative approaches to human health. Known for their ability to connect microscopic genetic variations with broader health implications, they often wear many hats and are seen as the cornerstone of precision medicine.",
    "A visionary scientist who seamlessly blends cutting-edge molecular research with clinical insights, navigating the intricate landscape of human biological variation with remarkable precision.They possess an uncanny ability to anticipate genetic risk factors, develop advanced diagnostic strategies, and inspire interdisciplinary teams to explore the frontiers of genetic understanding. Their approach combines advanced technological techniques with deep biological comprehension.",
    "A scientific maestro who transforms biological complexity into meaningful health insights. With laser-focused attention to detail and a panoramic view of human genomic landscapes, they design sophisticated research approaches that enhance disease understanding, foster personalized treatment strategies, and create sustainable paths to improved human health. Their scientific pursuit is both a rigorous methodology and an art of discovery.",
    "An exceptional professional who embodies the perfect blend of technological proficiency and compassionate scientific inquiry. They understand that biological research is not just about data and sequences, but about unraveling the profound mysteries of human health, creating hope for patients with complex genetic conditions, and building comprehensive understanding of hereditary mechanisms.",
    "A true scientific architect who designs intricate frameworks of molecular investigation, clinical interpretation, and therapeutic innovation. Their expertise lies in understanding the subtle interconnections between genetic variations, disease manifestations, and potential interventions. They can diagnose complex genetic disorders and implement transformative solutions that unlock new medical possibilities.",
    "A strategic thinker possessing an extraordinary capacity for genomic problem-solving. They view biological challenges not as insurmountable barriers, but as opportunities for scientific learning and breakthrough discoveries. Their ability to synthesize complex genetic information, make precise diagnostic choices, and lead advanced research makes them an invaluable asset in modern medical science.",
    "A dynamic researcher who excels at bridging biological theory with clinical application. They possess an innate talent for reading molecular dynamics, identifying hidden genetic factors, and creating alignment between scientific discoveries and potential therapeutic interventions. Their approach is both systematically precise and deeply empathetic.",
    "An adaptive scientist who thrives in the rapidly evolving field of molecular research, turning complex biological information into potential health breakthroughs. They are skilled at developing innovative research strategies, fostering interdisciplinary collaboration, and creating research ecosystems that can rapidly respond to emerging genetic understanding.",
    "A master of biological exploration, transforming raw molecular data into profound health insights. They understand the delicate balance between technological analysis and human complexity, using sophisticated research techniques to uncover, interpret, and potentially mitigate genetic health risks.",
    "A strategic navigator who guides scientific research through the complex terrain of human biology with remarkable skill and insight. Their expertise encompasses comprehensive understanding of molecular biology, advanced technological trends, and intricate human genetic variations. They design robust research frameworks that are both scientifically rigorous and potentially transformative for human health.",
    "This individual is an expert in understanding how inherited traits influence human health and disease. They analyze patterns within families to identify conditions that may be passed down through generations, offering critical insights for prevention and treatment.",
    "With exceptional attention to detail, this specialist deciphers complex biological information to uncover the root causes of inherited medical conditions. Their work enables accurate diagnoses and personalized care strategies.",
    "This professional focuses on understanding the relationship between inherited characteristics and health outcomes. Their expertise allows them to identify risks early, guiding interventions to improve patient well-being.",
    "By exploring patterns of inheritance and family histories, this expert identifies conditions that may affect individuals across their lifetimes. Their insights help families understand risks and make informed decisions about healthcare.",
    "This individual combines scientific expertise and clinical knowledge to uncover how traits are passed down and contribute to human health. They provide clarity in complex medical cases, paving the way for effective treatments.",
    "A specialist in inherited conditions, this professional identifies key biological markers to address health challenges. Their analytical skills help transform data into actionable medical solutions.",
    "This expert plays a critical role in understanding diseases that run in families, offering solutions for early detection and treatment. Their work improves outcomes by connecting biological information to real-world care.",
    "Focused on uncovering patterns of inheritance, this professional studies how certain traits and health conditions are transmitted across generations. Their findings support tailored approaches to diagnosis and prevention.",
    "With a talent for solving complex medical puzzles, this individual identifies underlying causes of inherited diseases. Their work bridges scientific research and clinical care, offering hope for affected families.",
    "This specialist excels at analyzing biological traits to identify risks for certain medical conditions. By studying family histories, they guide patients and clinicians toward effective prevention and care strategies."
]

# Combine both into JSON format
data = [{"text": text, "label": 0} for text in management_sentences] + [{"text": text, "label": 1} for text in genetics_sentences]

# Convert to JSON
output_json = json.dumps(data, ensure_ascii=False, indent=4)

# Save JSON file
output_path = "./description.json"

with open(output_path, "w", encoding="utf-8") as f:
    f.write(output_json)

print(f"JSON data successfully saved to {output_path}")